package commands

var helpLs = CommandHelp{
	Name:        "ls",
	Description: "List tasks",
	Usage: []string{
		"recur ls                    Show task dashboard",
		"recur ls --all              Show all tasks (completed and incomplete)",
		"recur ls --done             Show completed tasks",
		"recur ls --trash            Show deleted tasks",
		"recur ls --tags             List all tags with counts",
		"recur ls --projects         List all projects with counts",
		"recur ls --priorities       List all priorities with counts",
		"recur ls --today            Show tasks due today",
		"recur ls --tomorrow         Show tasks due tomorrow",
		"recur ls --overdue          Show overdue tasks",
		"recur ls --upcoming         Show upcoming tasks (next 7 days)",
		"recur ls --due <date>       Show tasks due on specific date",
		"recur ls --from <date>      Show tasks from date onwards",
		"recur ls --to <date>        Show tasks up to date",
		"recur ls --tag <tag>        Show tasks with specific tag",
		"recur ls --project <proj>   Show tasks in specific project",
		"recur ls --priority <pri>   Show tasks with specific priority",
		"recur ls --query <keyword>  Search tasks by keyword",
		"recur ls --note             Include notes in task list",
		"recur ls --export [path]    Export filtered tasks to CSV",
	},
	Options: []Option{
		{"-a, --all", "Show all tasks (completed and incomplete)"},
		{"-x, --done", "Show completed tasks"},
		{"--trash", "Show deleted tasks"},
		{"--tags", "List all tags with task counts"},
		{"--projects", "List all projects with task counts"},
		{"--priorities", "List all priorities with task counts"},
		{"--today", "Show tasks due today"},
		{"--tomorrow", "Show tasks due tomorrow"},
		{"--overdue", "Show overdue tasks"},
		{"--upcoming", "Show upcoming tasks (next 7 days)"},
		{"-d, --due <date>", "Show tasks due on specific date"},
		{"--from <date>", "Show tasks from date onwards (inclusive)"},
		{"--to <date>", "Show tasks up to date (inclusive)"},
		{"-t, --tag <tag>", "Filter by tag (can specify multiple)"},
		{"-p, --project <proj>", "Filter by project (can specify multiple)"},
		{"-P, --priority <pri>", "Filter by priority (can specify multiple)"},
		{"-q, --query <keyword>", "Search in task name, tag, project, and note"},
		{"-n, --note", "Include notes in task list"},
		{"--export [path]", "Export to CSV (auto-generates filename if not provided)"},
		{"-h, --help", "Show this help message"},
	},
	Examples: []string{
		"# Basic listing",
		"recur ls                        # Show dashboard",
		"recur ls --all                  # All tasks",
		"recur ls --done                 # Completed tasks",
		"recur ls --trash                # Deleted tasks",
		"",
		"# Metadata listings",
		"recur ls --tags                 # List all tags",
		"recur ls --projects             # List all projects",
		"recur ls --priorities           # List all priorities",
		"",
		"# Date filters",
		"recur ls --today",
		"recur ls --tomorrow",
		"recur ls --overdue",
		"recur ls --upcoming",
		"recur ls --due 2025-11-15",
		"recur ls --due tomorrow",
		"recur ls --due none             # Tasks with no due date",
		"recur ls --due recurring        # Recurring tasks",
		"recur ls --from 2025-11-15",
		"recur ls --to 2025-12-31",
		"recur ls --from today --to 2025-11-20",
		"",
		"# Attribute filters",
		"recur ls --tag work",
		"recur ls --project Home",
		"recur ls --priority urgent high",
		"recur ls --query meeting",
		"",
		"# Combined filters",
		"recur ls --today --note",
		"recur ls --tag work --project Office",
		"recur ls --from 2025-11-15 --tag work --priority high",
		"",
		"# Export to CSV",
		"recur ls --export                                 # recur_20250117_143022.csv",
		"recur ls --today --export                         # recur_today.csv",
		"recur ls --due 2025-11 --export                   # recur_202511.csv",
		"recur ls --tag work --priority high --export      # recur_work_high.csv",
		"recur ls --overdue --export overdue_tasks.csv     # Custom filename",
	},
}
