package commands

var helpRm = CommandHelp{
	Name:        "rm",
	Description: "Delete tasks",
	Usage: []string{
		"recur rm <id>               Delete a task",
		"recur rm <id1> <id2> ...    Delete multiple tasks",
		"recur rm --tag <tag>        Delete tasks by tag",
		"recur rm --project <proj>   Delete tasks by project",
		"recur rm --priority <pri>   Delete tasks by priority",
		"recur rm --due <date>       Delete tasks due on date",
		"recur rm --all              Delete all incomplete tasks",
		"recur rm --done             Delete all completed tasks",
		"recur rm --trash            Permanently delete all trashed tasks",
		"recur rm --purge            Permanently delete ALL tasks from database",
		"recur rm --undo <id>        Restore deleted task(s)",
		"recur rm --undo --tag <tag> Restore deleted tasks by filter",
	},
	Options: []Option{
		{"--all", "Delete all incomplete tasks"},
		{"--done", "Delete all completed tasks"},
		{"--trash", "Permanently delete all trashed tasks (cannot be undone)"},
		{"--purge", "Permanently delete ALL tasks from database (cannot be undone)"},
		{"--undo", "Restore deleted tasks (cannot combine with other operations)"},
		{"--today", "Delete tasks due today"},
		{"--tomorrow", "Delete tasks due tomorrow"},
		{"--overdue", "Delete overdue tasks"},
		{"--upcoming", "Delete upcoming tasks"},
		{"-d, --due <date>", "Delete tasks due on specific date"},
		{"--from <date>", "Delete tasks from date onwards"},
		{"--to <date>", "Delete tasks up to date"},
		{"-t, --tag <tag>", "Delete tasks with specific tag (can specify multiple)"},
		{"-p, --project <proj>", "Delete tasks in specific project (can specify multiple)"},
		{"-P, --priority <pri>", "Delete tasks with specific priority (can specify multiple)"},
		{"-q, --query <keyword>", "Delete tasks matching search"},
		{"-h, --help", "Show this help message"},
	},
	Examples: []string{
		"recur rm 1",
		"recur rm 1 2 3",
		"recur rm --tag work",
		"recur rm --project Home",
		"recur rm --priority urgent high",
		"recur rm --due today",
		"recur rm --from 2025-11-01 --to 2025-11-30",
		"recur rm --query meeting",
		"recur rm --tag work --due today",
		"recur rm --all",
		"recur rm --done",
		"recur rm --trash",
		"recur rm --purge",
		"recur rm --undo 1 2 3",
		"recur rm --undo --tag work",
		"recur rm --undo --query meeting",
	},
}
