package commands

var helpDone = CommandHelp{
	Name:        "done",
	Description: "Mark tasks as complete",
	Usage: []string{
		"recur done <id>              Complete a task",
		"recur done <id1> <id2> ...   Complete multiple tasks",
		"recur done --tag <tag>       Complete tasks by tag",
		"recur done --project <proj>  Complete tasks by project",
		"recur done --priority <pri>  Complete tasks by priority",
		"recur done --due <date>      Complete tasks due on date",
		"recur done --undo <id>       Unmark completed task(s)",
		"recur done --undo --tag <tag> Unmark completed tasks by filter",
	},
	Options: []Option{
		{"--today", "Complete tasks due today"},
		{"--tomorrow", "Complete tasks due tomorrow"},
		{"--overdue", "Complete overdue tasks"},
		{"--upcoming", "Complete upcoming tasks"},
		{"-d, --due <date>", "Complete tasks due on specific date"},
		{"--from <date>", "Complete tasks from date onwards"},
		{"--to <date>", "Complete tasks up to date"},
		{"-t, --tag <tag>", "Complete tasks with specific tag"},
		{"-p, --project <proj>", "Complete tasks in specific project"},
		{"-P, --priority <pri>", "Complete tasks with specific priority"},
		{"-q, --query <keyword>", "Complete tasks matching search"},
		{"--undo", "Unmark completed tasks as incomplete"},
		{"-h, --help", "Show this help message"},
	},
	Examples: []string{
		"recur done 1",
		"recur done 1 2 3",
		"recur done --today",
		"recur done --tag work",
		"recur done --project Home",
		"recur done --priority urgent",
		"recur done --due today",
		"recur done --query meeting",
		"recur done --tag work --due today",
		"recur done --undo 1 2 3",
		"recur done --undo --tag work",
		"recur done --undo --today",
	},
}
